### ISSUE TITLE
customize the container image version

### ISSUE THREAD

**Issue by shixud** [apache/streampark#1111]
### Search before asking

- [X] I had searched in the [feature](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Hello. When using the kubernetes application to create a job. Can I customize the container image version? Because when I use kubernetes version v1.11.1, I need to modify the mirror address of yaml myself to add the latest version.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
you can submit job with dynamic params:
-Dkubernetes.container.image.pull-policy=Always 

The process of streamx submitting k8s job is to generate a new image locally based on the basic image you provided and some configurations of your current job, then push it to the docker repository, and then start the flink job. This parameter is added to prevent you from modifying it. program, but the old program was deployed because the mirror was not updated in time.

---

streamx提交k8s任务的流程是先在本地基于你提供的基础镜像和你当前任务的一些配置，生成一个新的镜像，然后推送到docker仓库，然后启动flink任务，添加这个参数是为了防止你修改了程序，但是由于未及时更新镜像，而部署了旧的程序。

**Comment by shixud** [comment]
> 您可以使用动态参数提交作业： -Dkubernetes.container.image.pull-policy=Always
> 
> streamx提交k8s job的过程是根据你提供的基础镜像和你当前job的一些配置在本地生成一个新的镜像，然后push到docker仓库，然后启动flink job。添加此参数是为了防止您对其进行修改。程序，但是由于镜像没有及时更新而部署了旧程序。
> 
> streamx提交8个的基础任务和当前任务的一些任务是先在你提供的基础任务和当前任务，然后根据你的本地配置一个新的任务配置到仓库，启动链接，是为了让你阻止修改程序，但由于没有及时更新更新，而部署了旧的程序。

  It doesn't seem to be the problem. After I create a task with the execution mode of kubernetes application in streamx, I view the pod created by the task in the k8s cluster. But the pod status is unavailable. Prompt ImagePullBackOff: Back-off pulling image registry.cn -shenzhen.aliyuncs.com/user/job-name-xxx. At present, the reason why the mirror cannot be pulled down is probably because there is no version number. I can only manually modify the yaml file to add the latest label to the mirror address. I think streamx When creating this type of task, add the latest version number to the mirror address.

---

好像不是这个问题.我在streamx创建执行模式为kubernetes application的任务后.在k8s集群中查看该任务创建的pod.但是该pod状态是不可用的.提示ImagePullBackOff: Back-off pulling image registry.cn-shenzhen.aliyuncs.com/user/job-name-xxx.目前该镜像拉不下来的原因大概是没有版本号的.我只能手动修改yaml文件给镜像地址加上latest标签.我想的是streamx创建该类型的任务时在就在镜像地址后面加上latest版本号
