### ISSUE TITLE
[Feature] yarn-seesion 模式集群配置建议

### ISSUE THREAD

**Issue by wangzhen-wudangshan** [apache/streampark#1669]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

目前yarn-seesion 模式集群配置需要自己手动启动flink的 yarn-session命令，然后找到application ID,填写到集群ID里面，这样不够自动化。建议一气呵成，简化使用，减少误解。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wolfboys** [comment]
please use English.

**Comment by wangzhen-wudangshan** [comment]
Next time, please use English to solve the problems or bugs I raised. Urgently use. If it doesn't work, it will no longer be used. It is too unstable.

**Comment by wangzhen-wudangshan** [comment]
Next time I use English, please solve my problems or bugs. If it doesn't work, I won't use it anymore. It's too unstable.

**Comment by tisonkun** [comment]
Without concrete description, this is barely a wishing list. We don't host a wishing list in issues since they're not actionable. You can share your ideas at: https://github.com/apache/incubator-streampark/discussions/categories/general.

Also lock this conversation because although you tick the Code of Conduct, you're still threatening in this thread. We simply _not_ welcome this manner.
