### ISSUE TITLE
[Feature] Add application backup count keep strategy

### ISSUE THREAD

**Issue by GOODBOY008** [apache/streampark#3079]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Story:
With long time to use StreamPark to maintain jobs , the backup number is very large and user only to clean backup when disk usage is very high. So I want to add a strategy to auto clean backups like `jenkins` just keep the latest `N` backups.
 
Impl:
- Add a setting config perperty to application `Number of backup copies` , default is `5`. 
- Add a Scheduled job to clean application backup.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by GOODBOY008** [comment]
@wolfboys Can you give me some suggestions?

**Comment by wolfboys** [comment]
> @wolfboys Can you give me some suggestions?

thanks for you driving it.

The background of the job backup feature is as follows:

When a job is releasing, the last job will be backup for subsequent rollback operations. However, flink job has different deployment modes, The rollback implementations of various deployment modes are also different. The rollback feature has not been implemented yet, so currently it is simply a backup function. When a job is modified and released many times, a large number of backup files will be generated, which indeed need to be dealt with. Currently, there are three ways to solve this issue:

1) There is a backup list on the job details page, which shows all the backup records of the job. Each record has a delete button for users to manually delete.
2) We can use scheduled tasks, Regularly check the backup records of all jobs and delete them (We can default to keeping 3 or 5 job backups).
3) Since the job backup feature currently has no practical use (rollback operation not implemented), we can also disable the job backup feature.
