### ISSUE TITLE
[Feature] change deploy/docker/dockercompose image tag to dev

### ISSUE THREAD

**Issue by MingkeVan** [apache/streampark#3247]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

There is no arm64 arch in latest image, which cause problem in Mac M2.
<img width="1161" alt="image" src="https://github.com/apache/incubator-streampark/assets/22877598/c9193659-238d-414b-b689-0e5d9d2e3c06">

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caicancai** [comment]
Hello, thank you very much for your contribution.dev has arm64 arch. In response to this bug, we will fix the latest bug later.

**Comment by caicancai** [comment]
@MingkeVan Hello, thank you very much for finding this issue, indeed in 2.1.1 this branch build docker image does not support arm64, in the upcoming release of 2.1.2 has fixed this bug. Since 2.1.1 has been released and runs stably, it is not good to rebuild the image, which is not friendly to other users, you can try to build this image locally and use it. By the way, Streampark is very optimized for Mac m2 support

**Comment by wolfboys** [comment]
Answered
