### ISSUE TITLE
[Improve] Replace All Instances of "StreamPark" with "Apache StreamPark™" in Official Documentation

### ISSUE THREAD

**Issue by VampireAchao** [apache/streampark#3492]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The official documentation of StreamPark currently refers to the project as "StreamPark". To align with the recent rebranding efforts and to maintain consistency in all communications, it is proposed to update all instances of "StreamPark" in the official documentation to "Apache StreamPark™".

### Usage Scenario

This change will affect all users who refer to the official documentation for guidance, ensuring that they are familiar with the project's official name and branding.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LittleBunVerse** [comment]
assign me

**Comment by VampireAchao** [comment]
> assign me

done

**Comment by caicancai** [comment]
The original guide is https://www.apache.org/foundation/marks/guide#howoften.

The full form of an Apache project is "Apache Foo™" o "Apache Foo®"(if the trademark is registered). It should be used for the first and most prominent mentions, at least including:

Titles or subtitles, including web page title or description metadata.
The first and most prominent header elements within any major document section.
The first and most prominent callout, sidebar, or other types of highlighted blocks of content displayed to the user.
The first and most prominent uses in running or body text within the document.
Other mentions can use short form depending on the context and writing style.

Of course, using "Apache StreamPark" always and "Apache StreamPark™" for the first and most prominent mentions are correct, although it may sometimes become cumbersome.

The important part here is to make the decision based on the understanding of the policy, instead of taking others' words as a magic to pass the check.
