### ISSUE TITLE
[Feature] Resolve Maven dependencies in depth

### ISSUE THREAD

**Issue by shenyi0828** [apache/streampark#3684]
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-streampark/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

dependency example:   
a -> b1,b2
b1 -> c1,c2
b2 -> d1,d2,d3
when I set deps "a" in 'application dependency' . only a,b1,c1 is included, NoSuchMethod exception is raised for missing c1,c2,d1,d2,d3 .

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by shenyi0828** [comment]
![image](https://github.com/apache/incubator-streampark/assets/2778352/d674b850-53d8-4c91-9551-68ba5a940eec)

code from MavenTool.scala

I thinkd streampark can only resolve 1st level deps, not recursively

**Comment by shenyi0828** [comment]
![image](https://github.com/apache/incubator-streampark/assets/2778352/a04d1799-1226-4119-8952-9df22ac67302)

I have to set them all for first level deps, which is marked by red square

**Comment by wolfboys** [comment]
Thanks for your feedback. Indirect dependencies may lead to loading some unexpected dependencies, causing jar conflicts and job failures, making troubleshooting very troublesome. Therefore, only direct dependencies are loaded, so that users need to manually confirm the addition of any dependencies required by the job. If you have any good ideas, you are welcome to discuss them together.

**Comment by wolfboys** [comment]
Answered. If you have other questions, please feel free to discuss them.
